### PR TITLE
MTEST-1: Create Inventory Item

### PR DESCRIPTION
**Pull request by ashwinjv**
Pull Request to add features described by MTEST-1 Create Inventory Item story

### CODE REVIEW

**Comment by ashwinjv** [comment]
This is an open pull request, as I add more code to my branch, it should get updated. This is just a way to keep an account of the PR status

**Comment by ervinebalo** [comment]
interesting. I didnt realize a PR can be "left open" for further updates

**Comment by ashwinjv** [comment]
Yes, I can fix the failing test, commit that, and the PR testing would say it passes. Then add the next test for this story. It is usually when there is a discussion regarding a PR and a code review is done, and the author of the PR can make any change suggested. We might want to discuss when to create a PR (after we complete a story? or when we start?) , but today I wanted to see what happens :)

**Comment by ervinebalo** [comment]
I like the progression. It'll be a good learning experience for me. If I had a PR, you could provide feedback on if the thing I am doing can be more efficient, etc

**Comment by ashwinjv** [comment]
This pull request is for the master branch. Closing this pull request. I will create a new pull request with the different branch

**Pull request closed without merging**
